### ISSUE TITLE
Adding file of 'CONTRIBUTING.md' for the project

### ISSUE THREAD

**Issue by zhlhahaha** [imega-docker/base-builder#10]
Hi Irvis and Imega, we want to enable jq on ARM64 platform, but there is no 'CONTRIBUTING.md' here, so we are not able to contribute code here. Can you add the files?
Example：
https://github.com/hustcat/sriov-cni/blob/master/CONTRIBUTING.md
Guideline:
https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors

**Comment by zhlhahaha** [comment]
ping @irvis @iMega @lubinsz

**Comment by iMega** [comment]
@zhlhahaha could you please review the PR?

**Comment by iMega** [comment]
@zhlhahaha I'm glad to help you. Could you please close this issue if you think the matter is closed.

**Comment by zhlhahaha** [comment]
Thanks, the documents look find. I will close this issue. @iMega 
Also, can you take a look same issue in imega-docker/jq project when you have time?
https://github.com/imega-docker/jq/issues/3
