### ISSUE TITLE
Add support for ppc64le architecture

### ISSUE THREAD

**Issue by murilofv** [imega-docker/base-builder#7]
Since the following commit https://github.com/kubevirt/kubevirt/commit/881a3cb583ba21b4d687d4c5e4a0bf141c4cb36c the Kubevirt project is using the `jq` container. And I've been trying to enable support for ppc64le for Kubevirt in the pull request https://github.com/kubevirt/kubevirt/pull/2944 . Given `base-builder` is a dependency for `jq` I wondered if we could build a list manifest container that would point to both a amd64 and a ppc64le container image. I was thinking on leverage the Travis CI in order to build and deploy the images, I made a patch that does so, it works by checking if there is any existent image already built for amd64 / ppc64le for a particular tag, in case there are not, they are built and pushed to the docker hub, in case both are successful then it moves to next stage of building the manifest list and pushes it to the docker hub repo.

[patch-base-builder-add-support-ppc64le.txt](https://github.com/imega-docker/base-builder/files/4134405/patch-base-builder-add-support-ppc64le.txt)

I tested on a fork I did and a docker hub repo I set. Here is an example of the Travis CI and the images it built:

https://travis-ci.com/murilofv/base-builder/builds/146598692
https://hub.docker.com/r/murilofv/base-builder/tags

So the patch only pushes the image in case they already don't exist, so only when moving to a new release it will create a new container. Here is an example of attempting to do the same job when the images already exist:

https://travis-ci.com/murilofv/base-builder/builds/146600968 

So for this patch to work it would need setting up the DOCKER_USER / DOCKER_PASS in the Travis CI. In case they are not already set, would this be a concern? Also as a side note, given the nature of the patch and the fact there is already a tag 1.9.0 container it would cause the Manifest-release step of the build to fail as it is. So I would suggest to bump the version to 1.9.1 so it generates everything appropriately if there is no concern in doing so. Let me know if there are any suggestions / concerns and if the patch would be acceptable and I can do a pull request for it. I also intend to do a similar process for `jq` in case this would be an acceptable approach.

**Comment by iMega** [comment]
@murilofv done

**Comment by murilofv** [comment]
Thank you for the help! And from my part sorry, I wasn't even aware it was possible to do a reverse pull, I would have adjusted the pointers similarly to the patch attached to the issue and worked on any improvements you had in mind prior to submitting the PR. Let me know if there is any pending concerns that I could help. I see the base-builder and jq now has the manifest containing pointers for both archs in docker hub, should we close this issue?

**Comment by iMega** [comment]
I'm glad to help you but I think you've made more that me ;) I checked that it works fine. Could you please close this issue if you think the matter is closed.

**Comment by murilofv** [comment]
Yeap, the issue has been addressed, so closing it. Thank you again for the help!
